SpojDebug/Controllers/HomeController.cs
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SpojDebug.Core;
using SpojDebug.Core.User;
using SpojDebug.Service.Submission;
using SpojDebug.Service.User;

namespace SpojDebug.Controllers
{
    public class HomeController : Controller
    {
        private readonly ISubmissionService _submissionService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUserService _userService;

        public HomeController(ISubmissionService submissionService, UserManager<ApplicationUser> userManager, IUserService userService)
        {
            _submissionService = submissionService;
            _userManager = userManager;
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            var userInfo = _userService.GetCurrentUser(User);

            if(userInfo.Accounts == null || !userInfo.Accounts.Any())
            {
                return RedirectToAction("SpojAccountCenter", "Manage");
            }
            var response = await _submissionService.GetUserSubmissionAsync(userId);

            return View(response);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SpojDebug/Controllers/SubmissionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SpojDebug.Core.User;
using SpojDebug.Service.Submission;
using SpojDebug.Ultil.Exception;

namespace SpojDebug.Controllers
{
    public class SubmissionController : Controller
    {
        private readonly ISubmissionService _submissionService;
        private readonly UserManager<ApplicationUser> _userManager;

        public SubmissionController(ISubmissionService submissionService, UserManager<ApplicationUser> userManager)
        {
            _submissionService = submissionService;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> WhereFailerTakePlaceLoL(int? id)
        {
            if (id == null)
                throw new SpojDebugException("Id cannot be null, please try again!");
            var resonse = await _submissionService.GetFirstFailForFailerAsync(id.Value);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Search([Bind("SubmissionId")] int? submissionId)
        {
            if (submissionId == null)
                throw new SpojDebugException("Id cannot be null, please try again!");

            var userId = _userManager.GetUserId(User);
            var response = await _submissionService.SearchSubmssionAsync(userId, submissionId.Value);

            if (response.Data == null)
                throw new SpojDebugException("Submission not exist!");

            return View("~/Views/TestCase/WhereFailerTakePlace.cshtml", response);
        }

        [HttpPost]
        public async Task<IActionResult> SearchWithoutCheck([Bind("SubmissionId")] int? submissionId)
        {
            if (submissionId == null)
                throw new SpojDebugException("Id cannot be null, please try again!");

            var userId = _userManager.GetUserId(User);
            var response = await _submissionService.SearchSubmssionAsync(userId, submissionId.Value);
            await _submissionService.EnqueueToDownloadAsync(userId, submissionId.Value);
            response = await _submissionService.SearchSubmssionAsync(userId, submissionId.Value);
            if (response.Data == null)
                throw new SpojDebugException("Submission not exist!");

            return View("~/Views/TestCase/WhereFailerTakePlace.cshtml", response);
        }
    }
}

SpojDebug/Controllers/TestCaseController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SpojDebug.Core.User;
using SpojDebug.Service.TestCase;
using SpojDebug.Ultil.Exception;
using System.Threading.Tasks;

namespace SpojDebug.Controllers
{
    public class TestCaseController : Controller
    {
        private readonly ITestCaseService _testCaseService;
        private readonly UserManager<ApplicationUser> _userManager;

        public TestCaseController(ITestCaseService testCaseService, UserManager<ApplicationUser> userManager)
        {
            _testCaseService = testCaseService;
            _userManager = userManager;
        }
        
        [HttpGet]
        [ResponseCache(Duration = 1440)]
        public async Task<IActionResult> WhereFailerTakePlace(int? id)
        {
            if (id == null)
                throw new SpojDebugException("Id Null");

            var userId = _userManager.GetUserId(User); 
            var response = await _testCaseService.GetFirstFailForFailer(id.Value, userId);

            return View(response);
        }
    }
}

SpojDebug/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

SpojDebug/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SpojDebug/Views/Home/Index.cshtml
@model ApplicationResult<List<SubmissionHomeModel>>
@{
    ViewData["Title"] = "Home Page";
}
@*<h3 style="text-align:center">Vô chỗ <a href="/Manage/SpojAccountCenter">này</a> set up acc SPOJ mới lấy submission được nha</h3>
    <h5 style="text-align:center;color:red">Dùng search box để tìm cho nhanh</h5>
    <h5 style="text-align:center;color:red">Hiện chỉ hiển thị 10 bài chưa 100 ở list bên dưới, bài mới submit sẽ không cập nhật ngay trừ khi bạn search, không thì 10 phút bài mới được down</h5>*@
<br />


<div class="section">
    <form asp-controller="Submission" asp-action="Search" method="POST">
        <div class="form-group">
            <label>Cannot find your submission? Search here!</label>
            <input class="form-control" type="number" name="submissionId" placeholder="Submission Id" />
        </div>
        @*<p style="color:green">Dùng box này để search submission của mình, nếu submission chưa được download thì hệ thống sẽ tiến hành download trong 10s, nếu sau 10s mà không có chứng tỏ bạn không thể xem được hoặc đó là bug</p>*@
        <div class="form-group">
            <input class="btn btn-dark" type="submit" value="Search" />
        </div>
    </form>
</div>
<div class="section">

    <div class="table-wrapper">
        <table class="table sortable table-responsive table-spoj-debug center table-hover table-multiple-head-rows table-compact">
            <thead>
                <tr>
                    <th class="nowrap">SUBMISSION ID</th>
                    <th class="nowrap">PROBLEMSET</th>
                    <th class="nowrap">ACCEPTED</th>
                    <th class="nowrap">TOTAL</th>
                    <th class="nowrap">FIRST TEST FAIL</th>
                </tr>
            </thead>
            <tbody>
                @{
                    var count = 1;
                    foreach (var row in Model?.Data)
                    {
                        var cssClass = count % 2 == 1 ? "odd" : "even";
                        <tr class="@cssClass">
                            <td>@row.SubmissionId</td>
                            <td>@row.ProblemCode     </td>
                            <td>@row.AcceptedTestCase</td>
                            <td>@row.TotalTestCase</td>
                            @if (row.FirtFailTestCase == -1)
                            {
                                <td>@row.FirtFailTestCase</td>
                            }
                            else
                            {
                                <td style="font-weight:bold"><a asp-controller="TestCase" asp-action="WhereFailerTakePlace" asp-route-id="@row.SubmissionId">@row.FirtFailTestCase</a></td>
                            }
                        </tr>
                        count++;
                    }
                }

            </tbody>
        </table>
    </div>
</div>


@section Scripts {

    <!--===============================================================================================-->
    <script src="~/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/bootstrap/js/popper.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script>
        $('.js-pscroll').each(function () {
            var ps = new PerfectScrollbar(this);

            $(window).on('resize', function () {
                ps.update();
            })

            $(this).on('ps-x-reach-start', function () {
                $(this).parent().find('.table100-firstcol').removeClass('shadow-table100-firstcol');
            });

            $(this).on('ps-scroll-x', function () {
                $(this).parent().find('.table100-firstcol').addClass('shadow-table100-firstcol');
            });

        });




    </script>
    <!--===============================================================================================-->
    <script src="~/js/main.js"></script>


}